/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa;

import com.mysql.jdbc.Util;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import puntoventa.Models.Model_products;
import puntoventa.Models.Model_sales;

/**
 *
 * @author onlycparra
 */
public class WindowOutput extends javax.swing.JFrame {
    private int total=0;
    private Sale sale0=new Sale();
    private DefaultTableModel tm0=new DefaultTableModel();
    
    public WindowOutput(User user0){
        sale0.username=user0.username;
        sale0.name=user0.name;
        
        initComponents();
        
        this.setExtendedState(WindowOutput.MAXIMIZED_BOTH);
        this.setVisible(true);
        this.labelUser.setText(user0.name);
        this.inputBarcode.requestFocus();
        
        if(user0.level==3){
            this.btnProducts.setEnabled(true);
            this.btnProducts.setVisible(true);
            this.btnUsers.setEnabled(true);
            this.btnUsers.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup0 = new javax.swing.ButtonGroup();
        panelList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRecipe = new javax.swing.JTable();
        panelControls = new javax.swing.JPanel();
        btnProducts = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        inputBarcode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radAdd = new javax.swing.JRadioButton();
        radDel = new javax.swing.JRadioButton();
        btnLogout = new javax.swing.JButton();
        labelUser = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnEndSale = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        panelTotals = new javax.swing.JPanel();
        labelChange = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        inputCash = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        panelRecent = new javax.swing.JPanel();
        labelRecentName = new javax.swing.JLabel();
        LabelRecentValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Rapidito v2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1300, 600));

        panelList.setBackground(new java.awt.Color(253, 249, 129));

        tableRecipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableRecipe);

        javax.swing.GroupLayout panelListLayout = new javax.swing.GroupLayout(panelList);
        panelList.setLayout(panelListLayout);
        panelListLayout.setHorizontalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelListLayout.setVerticalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        panelControls.setBackground(new java.awt.Color(253, 194, 240));

        btnProducts.setText("Productos");
        btnProducts.setEnabled(false);
        btnProducts.setVisible(false);
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });

        btnUsers.setText("Usuarios");
        btnUsers.setEnabled(false);
        btnUsers.setVisible(false);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        inputBarcode.setNextFocusableComponent(inputCash);
        inputBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBarcodeActionPerformed(evt);
            }
        });

        jLabel8.setText("Código de Barra");

        radAdd.setBackground(new java.awt.Color(253, 194, 240));
        btnGroup0.add(radAdd);
        radAdd.setSelected(true);
        radAdd.setText("Añadir");
        radAdd.setFocusable(false);
        radAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAddActionPerformed(evt);
            }
        });

        radDel.setBackground(new java.awt.Color(253, 194, 240));
        btnGroup0.add(radDel);
        radDel.setText("Quitar");
        radDel.setFocusable(false);

        btnLogout.setBackground(new java.awt.Color(122, 2, 2));
        btnLogout.setForeground(new java.awt.Color(200, 200, 200));
        btnLogout.setText("Salir");
        btnLogout.setFocusable(false);
        btnLogout.setRequestFocusEnabled(false);
        btnLogout.setRolloverEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        labelUser.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUser.setText("Usuario");

        btnCancel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnCancel.setText("Cancelar Venta");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnEndSale.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        btnEndSale.setText("Finalizar Venta");
        btnEndSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndSaleActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panelControlsLayout = new javax.swing.GroupLayout(panelControls);
        panelControls.setLayout(panelControlsLayout);
        panelControlsLayout.setHorizontalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(btnEndSale, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radDel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelControlsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelControlsLayout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelControlsLayout.setVerticalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnProducts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radDel)
                            .addComponent(btnUsers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout))
                    .addGroup(panelControlsLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(7, 7, 7)))
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEndSale)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTotals.setBackground(new java.awt.Color(253, 249, 129));

        labelChange.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        labelChange.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelChange.setMinimumSize(new java.awt.Dimension(147, 56));
        labelChange.setPreferredSize(new java.awt.Dimension(147, 56));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel6.setText("Vuelto");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel5.setText("Paga con");

        inputCash.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        inputCash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputCash.setNextFocusableComponent(btnEndSale);
        inputCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCashActionPerformed(evt);
            }
        });
        inputCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCashKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel3.setText("TOTAL");

        labelTotal.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText("$ 00000");
        labelTotal.setToolTipText("");

        javax.swing.GroupLayout panelTotalsLayout = new javax.swing.GroupLayout(panelTotals);
        panelTotals.setLayout(panelTotalsLayout);
        panelTotalsLayout.setHorizontalGroup(
            panelTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                        .addComponent(labelChange, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(panelTotalsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputCash, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(panelTotalsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotal)))
                .addContainerGap())
        );
        panelTotalsLayout.setVerticalGroup(
            panelTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        panelRecent.setBackground(new java.awt.Color(145, 254, 140));

        labelRecentName.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        labelRecentName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        LabelRecentValue.setFont(new java.awt.Font("Ubuntu", 1, 56)); // NOI18N
        LabelRecentValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelRecentValue.setText("$ 0000");
        LabelRecentValue.setToolTipText("");

        javax.swing.GroupLayout panelRecentLayout = new javax.swing.GroupLayout(panelRecent);
        panelRecent.setLayout(panelRecentLayout);
        panelRecentLayout.setHorizontalGroup(
            panelRecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRecentName, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelRecentValue)))
                .addContainerGap())
        );
        panelRecentLayout.setVerticalGroup(
            panelRecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRecentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRecentValue)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRecent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRecent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelTotals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEndSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndSaleActionPerformed
        try {
            int change=Integer.parseInt(labelChange.getText().substring(2));
            System.out.println("Change: "+change);
            if(change>=0){
                Model_sales.storeSale(sale0);
                exportText(sale0);
                btnCancelActionPerformed(evt);
            }else{
                inputCash.setBackground(Color.red);
            }
        } catch (ClassNotFoundException | FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(WindowOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEndSaleActionPerformed

    private void inputCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCashActionPerformed

    private void radAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radAddActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        WindowProducts pAdmin=new WindowProducts();
        pAdmin.setVisible(true);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        WindowUsers uAdmin=new WindowUsers();
        uAdmin.setVisible(true);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        WindowLogin login=new WindowLogin("Usted ha salido del Sistema");
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void inputBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBarcodeActionPerformed
        try {
            Product prod0=Model_products.getProduct(this.inputBarcode.getText());
            if(prod0!=null){
                Sale_item item0=new Sale_item(prod0);
                if(radAdd.isSelected()){
                    this.LabelRecentValue.setText("$ "+Integer.toString(prod0.sale_price));
                    panelRecent.setBackground(Color.decode("#91fe8c"));
                    sale0.addItem(item0);
                }else{
                    this.LabelRecentValue.setText("-$ "+Integer.toString(prod0.sale_price));
                    panelRecent.setBackground(Color.decode("#ffaaaa"));
                    sale0.removeItem(item0.barcode);
                }
                this.labelRecentName.setForeground(Color.black);
                this.labelRecentName.setText(prod0.name);
                this.labelTotal.setText("$ "+Integer.toString(sale0.getTotal()));
                refreshTable(sale0);
            }else{
                this.labelRecentName.setForeground(Color.red);
                this.labelRecentName.setText("PRODUCTO DESCONOCIDO");
                this.LabelRecentValue.setText("");
            }
            this.inputBarcode.setText("");
            this.inputBarcode.requestFocus();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(WindowOutput.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_inputBarcodeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        sale0.items.clear();
        inputCash.setBackground(Color.white);
        inputCash.setText("");
        labelChange.setText("");
        labelRecentName.setText("");
        LabelRecentValue.setText("$ 0000");
        labelTotal.setText("$ 00000");
        refreshTable(sale0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void inputCashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCashKeyTyped
        Character c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
            getToolkit().beep();
        }else{
            inputCash.setBackground(Color.white);
            inputCash.setText(inputCash.getText()+c);
            evt.consume();
            int tot=Integer.parseInt(labelTotal.getText().substring(2));
            int cash=Integer.parseInt(inputCash.getText());
            labelChange.setText("$ "+Integer.toString(cash-tot));
        }
        if(c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE){
            inputCash.setText("");
            evt.consume();
            labelChange.setText("");
        }
    }//GEN-LAST:event_inputCashKeyTyped

    void refreshTable(Sale sale0){
        DefaultTableModel tm0=new DefaultTableModel();
        tm0.addColumn("Producto");
        tm0.addColumn("#");
        tm0.addColumn("$ unitario");
        tm0.addColumn("subtotal");
        this.tableRecipe.setModel(tm0);
        
        //this.tableRecipe.setModel(tablemodel0);
        for(Sale_item item:sale0.items){
            Object[] row0=new Object[4];
            row0[0]=item.name;
            row0[1]=item.quantity;
            row0[2]=item.sale_price;
            row0[3]=item.quantity*item.sale_price;
            tm0.addRow(row0);
        }
    }
    
    void exportText(Sale sale0) throws FileNotFoundException, UnsupportedEncodingException{
        String path=System.getProperty("user.home")+"/receipts/";
        System.out.println("Path: "+path);
        File dir=new File(path);
        dir.mkdirs();
        try (PrintWriter writer = new PrintWriter(path+now()+".txt", "UTF-8")) {
            writer.println("-------------------------------------------------------------");
            writer.println(">>          E L   C H O R O   D E L   B A R R I O          <<");
            writer.println("-------------------------------------------------------------");
            
            String name=sale0.name+"                        ";
            name=name.substring(0,24);
            writer.println(name+"                  "+now());
            writer.println("");
            
            for(Sale_item item:sale0.items){
                String prod=item.name+"                        ";
                prod=prod.substring(0,24);
                
                String quan="    "+Integer.toString(item.quantity);
                quan=quan.substring(quan.length()-4);
                
                String subtot="        "+Integer.toString(item.sale_price*item.quantity);
                subtot="$ "+subtot.substring(subtot.length()-8);
                
                writer.println(prod+"               x"+quan+"       "+subtot);
            }
            writer.println("");
            String tot = "        " + Integer.toString(sale0.getTotal());
            tot = "$ " + tot.substring(tot.length() - 8);
            writer.println("TOTAL----------------------------------------------"+tot);
        }
    }
    
    private static String now() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss");
        return sdf.format(cal.getTime());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRecentValue;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEndSale;
    private javax.swing.ButtonGroup btnGroup0;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnUsers;
    private javax.swing.JTextField inputBarcode;
    private javax.swing.JTextField inputCash;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelChange;
    private javax.swing.JLabel labelRecentName;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel panelControls;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelRecent;
    private javax.swing.JPanel panelTotals;
    private javax.swing.JRadioButton radAdd;
    private javax.swing.JRadioButton radDel;
    private javax.swing.JTable tableRecipe;
    // End of variables declaration//GEN-END:variables
}
